---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redit-clone
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: redit-clone-container
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redit-clone-container
    spec:
      containers:
      - image: rohanrustagi18/redditclone
        imagePullPolicy: Always
        name: todo-app-container
        ports:
        - containerPort: 3000
          protocol: TCP
      
---
apiVersion: v1
kind: Service
metadata:
  name: redit-clone-service
spec:
  selector:
      app.kubernetes.io/name: redit-clone-container
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30005
